# -*- coding: utf-8 -*-
"""Web_Scaping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/151suzIZF_-JMl669imwiP0vD96Talzou
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests

headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '3600',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'
    }

url = "https://economictimes.indiatimes.com/markets/stocks/recos"
req = requests.get(url, headers)
soup = BeautifulSoup(req.content, 'html.parser')
print(soup.prettify())

soup.find_all('h3')

tag = soup.find_all('h3')
print(tag)

d = [element.text for element in soup.find_all("h3")]
d

df = pd.DataFrame(d, columns=['buy'])

df = df.buy.str.split(',',expand=True)

df